# Generated by Django 3.1 on 2020-08-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=13)),
                ('timing', models.DateTimeField()),
            ],
        ),
    ]
