# Generated by Django 3.1 on 2020-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
