# Generated by Django 3.1 on 2020-08-29 11:56

import bookings_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_api', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=40, validators=[bookings_api.models.small_username]),
        ),
    ]
