# Generated by Django 3.1 on 2020-08-29 11:57

import bookings_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_api', '0003_auto_20200829_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[bookings_api.models.small_phonenum]),
        ),
    ]
