# Generated by Django 3.1 on 2020-08-29 16:13

import bookings_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_api', '0004_auto_20200829_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='timing',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True, validators=[bookings_api.models.validate_date]),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(null=True, validators=[bookings_api.models.validate_time]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
