# Generated by Django 3.1 on 2020-08-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_api', '0005_auto_20200829_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
